name: CI Frontend

on:
  push:
    branches:
      - feature/deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'

      - name: Install dependencies
        run: npm install

      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser

      - name: Run tests
        run: |
          npm install karma-cli -g
          npm install karma --save-dev
          npm install karma-chrome-launcher --save-dev
          npm install karma-jasmine --save-dev
          npm install karma-jasmine-html-reporter --save-dev
          npm test -- --no-watch --browsers=ChromeHeadless
